<?php

/**
 * @file
 * Contains vff.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vff_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vff module.
    case 'help.page.vff':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Views Formatter') . '</p>';
      return $output;

    default:
  }
}
